services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: url_shortener
      DB_USERNAME: urluser
      DB_PASSWORD: urlpassword
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: docker.arvancloud.ir/postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schemas/db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql

  redis:
    image: docker.arvancloud.ir/redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
